// Things Olivia has said. One shows each day, in turn.
// Add new ones anywhere in the list and push — keep the quotes and commas.
window.OLIVIA_SAYS = {
  name: "Olivia",
  quotes: [
    "You're boring, Dad.",
    "I'm full of quarters.",
    "Lightsaber banana.",
    "The Earth is just like an old grandma.",
    "Daddy, why don't we get a frog and suck away all the mosquitoes?",
    "My eyebrows are going to be really angry.",
    "This song is called Vacuum Clean the Nose.",
    "Let's plant a marshmallow tree.",
    "It's taco Tuesday!",
    "You have to wait for people!",
    "I really wanna buy an x-ray.",
    "Don't see me!",
    "You smell nice. You smell like chicken rice.",
    "Shhhh tahhh bahh bahh.",
    "My shark eats the asteroids.",
    "Why is the atmosphere angry???",
    "Cheetoh poop.",
    "I love rolly pollys. They don't bite.",
    "Can we go to Saturn?",
    "Why do they DO that?! Why, Daddy?",
    "Pootsah is Daddy, Teetah is Vivi, Mommy is… Pettsah. Vivi is Tootsah.",
    "Daddy, can I draw the virus? I like the viruses.",
    "I'm so strong. Look at my legs, they are so long.",
    "I have a lot of energy, hehehe.",
    "I'm not old! I'm new!",
    "My name is Orange Juice Pop.",
    "Mommy, do you have viruses?",
    "You're growing shorter. You're going to be a kid again.",
    "Mine is beautifuler. And perfecter.",
    "I can take really good care of my family. I'm the biggest kid.",
    "What does a cloud eat?",
    "Shrimps are from the water. They dig.",
    "Don't dance when we are eating.",
    "I'm not an angel or Sleeping Beauty.",
    "I have so much love. I have one hundred love. And I got more coming. Twenty-two hundred!",
    "That's a wobbegong shark!",
    "When you jump up and down, the whole city jumps up and down.",
    "Mom, this is you, covered in mosquito bites.",
    "I'll catch you if you fall.",
    "Butterfly demon shower.",
    "I really, really wanna be 5.",
    "My brain is sleeping right now. It had so much fun."
  ]
};
